// Turns the E2E screenshots (e2e/screenshots, regenerated by `npm run test:e2e`) into light WebP
// copies for the README in docs/screenshots.
import sharp from "sharp";
import { mkdir, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = path.join(root, "e2e", "screenshots");
const out = path.join(root, "docs", "screenshots");
await mkdir(out, { recursive: true });
const files = (await readdir(src)).filter((f) => f.endsWith(".png") && !f.includes("-full"));
for (const f of files) {
  const mobile = f.startsWith("mobile");
  const target = path.join(out, f.replace(/\.png$/, ".webp"));
  const info = await sharp(path.join(src, f))
    .resize({ width: mobile ? 540 : 1600, withoutEnlargement: true })
    .webp({ quality: 80, effort: 6 })
    .toFile(target);
  console.log(path.basename(target), `${Math.round(info.size / 1024)} KB`);
}
